name: CI-Dispatch

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    strategy:
      matrix:
        repo: ['wlaunchELF', 'Open-PS2-Loader', 'isjpcm', 'Fceumm-PS2']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Send Compile action
      run: |
        export DISPATCH_ACTION="$(echo run_build)"
        echo "NEW_DISPATCH_ACTION=$DISPATCH_ACTION" >> $GITHUB_ENV
    - name: Dispatch to organization repositories
      if: ${{ github.event_name }} != 'repository_dispatch'
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository_owner }}/${{ matrix.repo }}
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}"}'

    - name: "Dispatch to organization repositories (with payload)"
      if: ${{ github.event_name }} == 'repository_dispatch'
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: ${{ github.repository_owner }}/${{ matrix.repo }}
        token: ${{ secrets.DISPATCH_TOKEN }}
        event-type: ${{ env.NEW_DISPATCH_ACTION }}
        client-payload: '{"ref": "${{ github.ref }}", "parent:" "${{ github.event.client_payload.parent }}", "parent_sha": "${{ github.event.client_payload.parent_sha }}"}'
